ompute Mgas within radius+err in kpc
mg_r500, mg_lo, mg_hi =depr.Mgas(radius = 1123., radius_err=50.)
ValueError: too many values to unpack (expected 3)
The solution is 
return mg,mgl,mgh  instead of return mg,mgl,mgh,rho